### PR TITLE
Remove dependency on Postgres for testing

### PR DESCRIPTION
**Pull request by celliott181**
I took care of updating all dependencies and refactoring testing to use SQLite in memory rather than Postgres, allowing much better test portability.

### CODE REVIEW

**Comment by celliott181** [comment]
This breaks TravisCI config for Postgres since it drops the Postgres requirement. We should probably discuss whether to accept and fix tests to handle SQLite or Postgres depending on how they're being run, or lose out on those who don't want to set up an entire Postgres DB to work on this when it supports so many other dialects.

Personally I'm all for using SQLite as the "dev" test environment and then allowing the full suite to run using Postgres on Travis.

**Comment by thebergamo** [comment]
@gelliott181 thanks very much for your contribution!

I'm agree about using SQLite instead of the entire Postgres in development and in test.
Can you just remove the `^` in the package.json? and rebase your commits into just one?

**Comment by celliott181** [comment]
Squashed the commits and removed semver selectors.

**Comment by thebergamo** [comment]
Perfect!! Now I can merge it!

**Comment by thebergamo** [comment]
Thanks again for your PR :) I'm glad to see devs using k7!!

**Pull request merged**
